name: run_unit_tests

on:
  push:
    branches:
      - 'master'

jobs:
  apk_after_tests:
    if: startsWith(github.head_ref, 'release/') == true
    name: Build APK after tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests and apk build
        run: | 
          ./gradlew :app:test
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

